ur5:
  kinematics_solver: blitz_robot_ur5/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.02
  kinematics_solver_timeout: 0.2
#ur5:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.1
